### PR TITLE
Glm/readout

### PR DESCRIPTION
**Pull request by glehmannmiotto**
Few schema modifications to support some features needed in the areas of the readout map.

### CODE REVIEW

**Review by gcrone — COMMENTED** [review]
It seems rather out of place to have `StreamEmulationParameters` in the readout map. It contains fields that you may wish to vary from session to session whereas the rest of the map is more static, just defining how the detector is wired.

**Comment by glehmannmiotto** [comment]
Good point @gcrone . Where do you think that we should link it to? Maybe the DataReaderConf on appdal?

**Comment by gcrone** [comment]
Yes, I think that would make sense. The DataReader has an emulated flag associated with it so having the emulator config associated with DataReaderConf would be logical.

**Comment by glehmannmiotto** [comment]
cordial and appdal updates accordingly.

**Review by gcrone — APPROVED** [review]
All looks good now

**Pull request merged**
